### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#108]
**Describe the bug**
There is a crash incompatibility with Optifine in the beta. 
Note: This bug has not been reconfirmed for a couple months. 

**To Reproduce [Optional]**
Install optifine and the crossroads beta. Open any world. 

**Additional context [Optional]**
Relevant section of crash log:

`at net.minecraft.client.renderer.FluidBlockRenderer.func_178268_a(FluidBlockRenderer.java:41)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_195410_a(BlockRendererDispatcher.java:154)
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16)
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$2732/1231160694.run(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$2856/569731617.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)`

**Comment by Da-Technomancer** [comment]
Noting that this bug has not been reconfirmed for the MC1.15+ version, which overhauled the rendering.

If someone with a valid forge/optifine instance could test this, this issue could be updated.
