### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by StrangerSon712** [Da-Technomancer/Crossroads#134]
**Describe the bug**

**To Reproduce [Optional]**

**Expected behavior [Optional]**

**Screenshots [Optional]**

**Additional context [Optional]**

**Comment by StrangerSon712** [comment]
Bug report: ---- Minecraft Crash Report ----
// But it works on my machine.

Time: 1/12/21 1:18 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lcom/Da_Technomancer/essentials/tileentities/LinkHelper;
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_74] {}
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_74] {}
	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_74] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4-forge-35.1.36.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
Caused by: java.lang.ClassNotFoundException: com.Da_Technomancer.essentials.tileentities.LinkHelper
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_74] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
	... 32 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
		at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_74] {}
		at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_74] {}
		at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_74] {}
		at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74] {}
		at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4-forge-35.1.36.jar:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_74] {}
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_74] {}
	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_74] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4-forge-35.1.36.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1002557472 bytes (956 MB) / 1711276032 bytes (1632 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.36.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.36
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.36-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |LOAD_REGIS|NOSIGNATURE
		theoneprobe-1.16-3.0.4-beta.jar                   |The One Probe                 |theoneprobe                   |1.16-3.0.4-beta     |LOAD_REGIS|NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |LOAD_REGIS|NOSIGNATURE
		mana-and-artifice-1.2.1.8.jar                     |Mana and Artifice             |mana-and-artifice             |1.2.1.8             |LOAD_REGIS|NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |LOAD_REGIS|NOSIGNATURE
		curios-forge-1.16.4-4.0.2.1.jar                   |Curios API                    |curios                        |1.16.4-4.0.2.1      |LOAD_REGIS|NOSIGNATURE
		tetra-1.16.4-3.5.3.jar                            |Tetra                         |tetra                         |3.5.3               |LOAD_REGIS|NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |LOAD_REGIS|NOSIGNATURE
		essentials-1.16.4-2.9.6.jar                       |Essentials                    |essentials                    |1.16.4-2.9.6        |LOAD_REGIS|NOSIGNATURE
		create-mc1.16.3_v0.3b.jar                         |Create                        |create                        |mc1.16.3_v0.3b      |LOAD_REGIS|NOSIGNATURE
		Xaeros_Minimap_20.28.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.28.1             |LOAD_REGIS|NOSIGNATURE
		XaerosWorldMap_1.11.3_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.3              |LOAD_REGIS|NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |LOAD_REGIS|NOSIGNATURE
		Controlling-7.0.0.9.jar                           |Controlling                   |controlling                   |7.0.0.9             |LOAD_REGIS|NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |LOAD_REGIS|NOSIGNATURE
		alexsmobs-1.4.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.4.1               |LOAD_REGIS|NOSIGNATURE
		rats-7.0.4-1.16.3.jar                             |Rats                          |rats                          |7.0.4               |LOAD_REGIS|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |LOAD_REGIS|NOSIGNATURE
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |LOAD_REGIS|NOSIGNATURE
		tombstone-6.0.2.jar                               |Corail Tombstone              |tombstone                     |6.0.2               |LOAD_REGIS|NOSIGNATURE
		charginggadgets-1.3.0.jar                         |Charging Gadgets              |charginggadgets               |1.3.0               |LOAD_REGIS|NOSIGNATURE
		logisticslasers-1.0.8.jar                         |Logistics Lasers              |logisticslasers               |1.0.8               |LOAD_REGIS|NOSIGNATURE
		buildinggadgets-3.7.2.jar                         |Building Gadgets              |buildinggadgets               |3.7.2               |LOAD_REGIS|NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |LOAD_REGIS|NOSIGNATURE
		mininggadgets-1.7.1.jar                           |Mining Gadgets                |mininggadgets                 |1.7.1               |LOAD_REGIS|NOSIGNATURE
		crossroads-1.16.4-2.6.2.jar                       |Crossroads                    |crossroads                    |version             |LOAD_REGIS|NOSIGNATURE
		forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |LOAD_REGIS|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-292.jar                                |Quark                         |quark                         |r2.4-292            |LOAD_REGIS|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |LOAD_REGIS|NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |LOAD_REGIS|NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |LOAD_REGIS|NOSIGNATURE
	Crash Report UUID: 8025e565-f32a-44c6-b941-2615a0cc663d
	Launched Version: 1.16.4-forge-35.1.36
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-12.0.24 355.11.10.50.10.103, NVIDIA Corporation
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz

**Comment by StrangerSon712** [comment]
I updated and that happened.

**Comment by Da-Technomancer** [comment]
Your version of Crossroads requires Essentials 2.10.0 or newer, you're using 2.9.6. Update your Essentials and it should launch fine.
