### ISSUE TITLE
Circuit Wire Plate combined with Redstone Temperature Regulator causes game crash

### ISSUE THREAD

**Issue by NHblock714** [Da-Technomancer/Crossroads#295]
Game crashes when Circuit Wire Plate provides circuit signal to Redstone Temperature Regulator.

![_O344B05XR8A1CUZKNO@NRK](https://github.com/user-attachments/assets/4d12bc70-756a-44f4-9f4a-97e772b687d2)

[minecraft-exported-logs-2024-08-09T18-33-59.log](https://github.com/user-attachments/files/16560037/minecraft-exported-logs-2024-08-09T18-33-59.log)

**Comment by Random-Scientist** [comment]
this is an extremely odd bug. Would you mind posting the mod version, (neo) forge version and MC version you see this behavior on?

```
[18:33:15] [Server thread/INFO]: Redirecting com/Da_Technomancer/essentials/blocks/redstone/CircuitTileEntity$Orient
[18:33:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null
```
(this section from the log seems to be the root of the issue)

**Comment by Random-Scientist** [comment]
Since this is an Essentials issue and this is the Crossroads repo, I'll close this issue here. Let's move further discussion to https://github.com/Crossroads-Development/Essentials/issues/100
