### ISSUE TITLE
Removing/adding heat sources with no block form via crafttweaker isn't working

### ISSUE THREAD

**Issue by Saereth** [Da-Technomancer/Crossroads#89]
My ct scripts:
`import mods.crossroads.EnvHeatSource;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

print("---------------CrossRoads Start------------------");

	#remove flowing lava as a heat source
	EnvHeatSource.removeRecipe(<minecraft:flowing_lava>);

	#add liquid glass as a heat source
	EnvHeatSource.addRecipe(<forestry:fluid.glass>, <tconstruct:clear_glass>, 1000, 3000);`

Unfortunately flowing lava still turns to cobble and provides heat and the fluid glass does not provide heat and cool to glass. Although crafttweaker does recognize all the syntax as correct (no errors in the logs)

version is crossroads 1.11.0. Let me know if I can provide any additional info

**Comment by Da-Technomancer** [comment]
When the script runs, does it print out the "----CrossRoads Start------" in the log correctly? Assuming it does, does it print out "Removing Environmental Heat recipe for Flowing Lava" (or similar name) in the log? Does it print the "Adding Environmental Heat recipe for Molten Glass" (or similar name) in the log?

Just trying to isolate the issue.

**Comment by Saereth** [comment]
Ah I was actually looking at the clientside loginstead of server side, there was an error. It does print out the crossroads start but then throws a null pointer, here is the full error message thrown in the crafttweaker log:

[INITIALIZATION][SERVER][INFO] ---------------CrossRoads Start------------------
[INITIALIZATION][SERVER][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: crossroads.zs}: null
java.lang.NullPointerException
	at Crossroads.__script__(crossroads.zs:8)
	at __ZenMain__.run(Crossroads)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:174)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:68)
	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:62)
	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:115)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_931_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Saereth** [comment]
little more info, I removed the removal (line 8) and now I get
[INITIALIZATION][CLIENT][INFO] Adding Environmental Heat recipe for forestry:fluid.glass
so it seems as though the recipe was added for that, but it's not working as a valid heat source:
https://imgur.com/a/3H7YIbt

**Comment by Da-Technomancer** [comment]
Is JEI showing the recipe as being added? When you look at recipes for clear glass (or press u on heat exchanger) do you see molten glass->clear glass?

**Comment by Saereth** [comment]
https://imgur.com/a/G78XF7k

yes, it does appear to be showing up in jei

**Comment by Da-Technomancer** [comment]
This appears to only be an issue when the ingredient block is a liquid. For example, when the ingredient is snow or obsidian the integration seems to be working fine.

**Comment by Da-Technomancer** [comment]
As it would turn out, the issue isn't liquids per se as all blocks with no item form (which includes liquids, but also fire, top halves of doors, etc.). Crafttweaker itself doesn't really have a way to specify blocks like that in scripts, as it tries to interpret things like <minecraft:stone> as the stone item before converting it to the stone block. However, ContentTweaker, an addon for CraftTweaker by the same dev, does have a way. I'm adding support for ContentTweaker's method, which is if either the input or output is block with no item form, you can specify it as <block:minecraft:fire>. To do this, people making scripts will have to call the ZenMethods in mods.crossroads.AdvEnvHeatSource, which will only be available if ContentTweaker is installed. Without ContentTweaker, only mods.crossroads.EnvHeatSource will be available, which does not allow specifying things like liquids or fire.

**Comment by Saereth** [comment]
perfect thanks, we are using content tweaker so this is a great help
